resources:
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: smoke-tests-pipeline
  type: git
  source:
    uri: https://github.com/marcus-sds/cf-smoke-tests-concourse.git
    branch: master
- name: every-10-minutes
  type: time
  source: {interval: 100m}
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-alert-webhook))

jobs:
- name: run-smoke-tests
  plan:
  - get: cf-smoke-tests
  - get: smoke-tests-pipeline
  - get: every-10-minutes
    trigger: true
  - task: run-smoke-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang, tag: 1.8.3}
      params:
        SYSTEM_DOMAIN: ((system-domain))
        APP_DOMAIN: ((app-domain}}
        cf_admin_passwd: ((cf-admin-passwd))
        CONFIG: "/tmp/smoke-tests.json"
      inputs:
        - name: cf-smoke-tests
        - name: smoke-tests-pipeline
      run:
        path: smoke-tests-pipeline/scripts/run-smoke-tests.sh
    on_failure:
      put: slack-alert
      params:
        channel: ((slack-channel))
        text: |
          :x: $BUILD_JOB_NAME for $BUILD_PIPELINE_NAME is FAILED
        username: "concourse"
